.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/run_docker_build.sh, .gitattributes, README.md
Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #7.
Here's a checklist to do before merging.
Fixes #7
=> MNT: rerender

recipe/conda_build_config.yaml
This is mostly here to show how the CPU build must be configured. Will also make it clearer what is done when adding the GPU builds alongside the CPU build.
Checklist
=> Explicitly specify Docker image for the build

.azure-pipelines/build_steps.sh, recipe/meta.yaml, recipe/yum_requirements.txt
=> Fix typo in libibverbs-devel yum requirement

.github/CODEOWNERS, README.md, recipe/meta.yaml
=> Add @quasiben as a maintainer

recipe/meta.yaml, recipe/patches/PR_4137.patch, recipe/patches/PR_4366.patch, recipe/patches/PR_4431.patch
=> Backport patches 1.7.0rc1

recipe/meta.yaml
cc @quasiben @pentschev @madsbk
Checklist
=> Release ucx-py 0.3

.scripts/build_steps.sh, recipe/meta.yaml, recipe/yum_requirements.txt
Fixes https://github.com/conda-forge/ucx-split-feedstock/issues/49
Checklist
=> Rebuild with CDT of libibcm

.scripts/build_steps.sh, recipe/meta.yaml, recipe/yum_requirements.txt
Fixes https://github.com/conda-forge/ucx-split-feedstock/issues/49
Checklist
=> Rebuild with CDT of libibcm (for RC)

recipe/install_ucx.sh, recipe/meta.yaml
=> Explicitly build libnuma support

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_cuda_compiler_version10.2.yaml, README.md, recipe/conda_build_config.yaml
=> Build CUDA 10.2 Support

recipe/install_ucx.sh
=> Quote `cuda_compiler_version` environment variable

.scripts/run_docker_build.sh, recipe/meta.yaml
=> Release 1.8.0

recipe/meta.yaml
=> Release 1.9.0

README.md, recipe/meta.yaml
Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #107.
Here's a checklist to do before merging.
Closes #107
=> Release 1.13.1

recipe/meta.yaml
=> Update to UCX v1.14.1

recipe/meta.yaml
=> update 11.2 to 11.8 to test migrator fix

recipe/meta.yaml
=> Update cuda_compiler_version logic.

recipe/meta.yaml
=> Update to v1.15.0

.ci_support/migrations/rdma_core51.yaml, recipe/meta.yaml
=> Update to v1.16.0

.github/CODEOWNERS, README.md, recipe/meta.yaml
Add pentschev (myself) as maintainer.
=> Add pentschev as maintainer

.gitignore, .scripts/run_docker_build.sh, build-locally.py, recipe/meta.yaml, recipe/ucx-post-link.sh
Closes #208 
@leofang just to double check, do we need to bump the build number here, I wasn't quite sure what the exact process is. Please let me know and I'll make any further changes that are needed. 
Checklist
=> Clarify message for when scenarios where cuda might be present
